---
    ansible_ssh_private_key_file: "/home/ec2-user/.ssh/k8s_key"
    ansible_ssh_common_args: "-o ProxyCommand='ssh -i/home/ec2-user/.ssh/bastion_host_key -W %h:%p ec2-user@{{ hostvars[groups['tag_bastion_host'][0]].public_ip_address }}'"