---
ansible_ssh_private_key_file: "/home/ec2-user/.ssh/bastion_host_key"
ansible_ssh_common_args: "-o ProxyCommand='ssh -i/home/ec2-user/.ssh/bastion_host_key -W %h:%p ec2-user@{{ public_ip_address }}'"
ansible_user: ec2-user